nohup: ignoring input
INFO:     Started server process [98925]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
Service embedding initialized
Tentative de connexion classique...
Connexion classique réussie à : pg-sae-sae3.i.aivencloud.com
INFO:     46.193.64.108:59943 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:59943 - "GET /books/topbook/30 HTTP/1.1" 200 OK
INFO:     46.193.64.108:60048 - "GET /books/topbook/30 HTTP/1.1" 200 OK
INFO:     47.76.40.1:44886 - "GET /.env HTTP/1.1" 404 Not Found
INFO:     47.76.40.1:44884 - "GET /.env HTTP/1.1" 404 Not Found
INFO:     47.76.40.1:44882 - "GET /.env HTTP/1.1" 404 Not Found
INFO:     198.235.24.221:60886 - "GET / HTTP/1.1" 200 OK
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
INFO:     138.197.15.3:41716 - "GET /aaa9 HTTP/1.1" 404 Not Found
INFO:     138.197.15.3:34030 - "GET /aab8 HTTP/1.1" 404 Not Found
INFO:     138.197.15.3:34040 - "GET / HTTP/1.1" 200 OK
INFO:     167.94.145.110:34684 - "GET / HTTP/1.1" 200 OK
INFO:     167.94.145.110:60524 - "GET / HTTP/1.1" 200 OK
INFO:     167.94.145.110:60546 - "GET /static/favicon.ico HTTP/1.1" 200 OK
INFO:     167.94.145.110:60560 - "GET /favicon.ico HTTP/1.1" 200 OK
INFO:     167.94.145.110:60562 - "PRI %2A HTTP/2.0" 404 Not Found
WARNING:  Invalid HTTP request received.
INFO:     103.203.57.20:45214 - "GET / HTTP/1.1" 200 OK
INFO:     79.95.86.227:55968 - "GET / HTTP/1.1" 200 OK
INFO:     79.95.86.227:55968 - "GET /static/css/styles.css HTTP/1.1" 200 OK
INFO:     79.95.86.227:55978 - "GET /static/css/body-styles.css HTTP/1.1" 200 OK
INFO:     79.95.86.227:55968 - "GET /static/css/carrousel.css HTTP/1.1" 200 OK
INFO:     79.95.86.227:55988 - "GET /static/js/carrousel.js HTTP/1.1" 200 OK
INFO:     79.95.86.227:55998 - "GET /static/js/body-scripts.js HTTP/1.1" 200 OK
INFO:     79.95.86.227:55988 - "GET /static/favicon.ico HTTP/1.1" 200 OK
INFO:     79.95.86.227:55998 - "GET /books/topbook/30 HTTP/1.1" 200 OK
INFO:     79.95.86.227:55998 - "GET /static/notfound.jpg HTTP/1.1" 200 OK
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /books/v1/volumes?q=isbn:9780310269526 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /books/v1/volumes?q=isbn:9780441020652 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /books/v1/volumes?q=isbn:9780006510420 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /books/v1/volumes?q=isbn:9781912408238 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /books/v1/volumes?q=isbn:9780451210555 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /books/v1/volumes?q=isbn:9780440416791 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /books/v1/volumes?q=isbn:9781416580515 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /books/v1/volumes?q=isbn:9780385346993 HTTP/1.1" 200 None
INFO:     79.95.86.227:41012 - "GET /books/search?query=Harr&skip=0&limit=20 HTTP/1.1" 200 OK
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /books/v1/volumes?q=isbn:9780006473244 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com:443
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /books/v1/volumes?q=isbn:9780765311955 HTTP/1.1" 200 None
INFO:     79.95.86.227:55990 - "GET /books/search?query=Ha&skip=0&limit=20 HTTP/1.1" 200 OK
INFO:     79.95.86.227:55990 - "GET /books/search?query=Harry&skip=0&limit=20 HTTP/1.1" 200 OK
INFO:     79.95.86.227:41574 - "GET / HTTP/1.1" 200 OK
INFO:     79.95.86.227:41574 - "GET /books/topbook/30 HTTP/1.1" 200 OK
INFO:     79.95.86.227:41574 - "GET /docs HTTP/1.1" 200 OK
INFO:     79.95.86.227:41574 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     79.95.86.227:45156 - "GET /install HTTP/1.1" 200 OK
INFO:     79.95.86.227:45156 - "GET /favicon.ico HTTP/1.1" 200 OK
INFO:     79.95.86.227:54900 - "GET / HTTP/1.1" 200 OK
INFO:     79.95.86.227:54900 - "GET /books/topbook/30 HTTP/1.1" 200 OK
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
INFO:     170.64.234.106:32966 - "GET / HTTP/1.1" 200 OK
INFO:     170.64.234.106:32976 - "GET /login HTTP/1.1" 404 Not Found
INFO:     46.193.64.108:65035 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:65034 - "GET /static/css/styles.css HTTP/1.1" 304 Not Modified
INFO:     46.193.64.108:65035 - "GET /static/css/body-styles.css HTTP/1.1" 304 Not Modified
INFO:     46.193.64.108:65036 - "GET /static/css/carrousel.css HTTP/1.1" 304 Not Modified
INFO:     46.193.64.108:65034 - "GET /static/js/body-scripts.js HTTP/1.1" 304 Not Modified
INFO:     46.193.64.108:65037 - "GET /static/js/carrousel.js HTTP/1.1" 304 Not Modified
INFO:     46.193.64.108:65037 - "GET /books/topbook/30 HTTP/1.1" 200 OK
INFO:     46.193.64.108:65037 - "GET /static/notfound.jpg HTTP/1.1" 304 Not Modified
INFO:     46.193.64.108:65037 - "GET /install HTTP/1.1" 200 OK
INFO:     46.193.64.108:65037 - "GET /favicon.ico HTTP/1.1" 200 OK
INFO:     46.193.64.108:56918 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56918 - "GET /static/css/styles.css HTTP/1.1" 304 Not Modified
INFO:     46.193.64.108:56920 - "GET /static/css/body-styles.css HTTP/1.1" 304 Not Modified
INFO:     46.193.64.108:56921 - "GET /static/css/carrousel.css HTTP/1.1" 304 Not Modified
INFO:     46.193.64.108:56922 - "GET /static/js/carrousel.js HTTP/1.1" 304 Not Modified
INFO:     46.193.64.108:56923 - "GET /static/js/body-scripts.js HTTP/1.1" 304 Not Modified
INFO:     46.193.64.108:56923 - "GET /books/topbook/30 HTTP/1.1" 200 OK
INFO:     46.193.64.108:56923 - "GET /static/notfound.jpg HTTP/1.1" 304 Not Modified
INFO:     46.193.64.108:65502 - "GET /books/topbook/30 HTTP/1.1" 200 OK
INFO:     45.84.139.54:33192 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56932 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56933 - "GET /static/favicon.ico HTTP/1.1" 304 Not Modified
INFO:     46.193.64.108:56932 - "GET /books/topbook/30 HTTP/1.1" 200 OK
INFO:     45.129.35.237:11978 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56961 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56961 - "GET /books/topbook/30 HTTP/1.1" 200 OK
INFO:     46.193.64.108:56961 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56961 - "GET /books/topbook/30 HTTP/1.1" 200 OK
INFO:     46.193.64.108:56961 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56962 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56963 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56964 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56965 - "GET / HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.9/dist-packages/starlette/_utils.py", line 76, in collapse_excgroups
  |     yield
  |   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 182, in __call__
  |     recv_stream.close()
  |   File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 767, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |   File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |   File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 112, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 182, in __call__
    |     recv_stream.close()
    |   File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    |     self.gen.throw(type, value, traceback)
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 179, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "/root/sae/Sae_3A/python/script/Api/main.py", line 78, in dispatch
    |     return await call_next(request)
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 154, in call_next
    |     raise app_exc
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 141, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 85, in __call__
    |     await self.app(scope, receive, send)
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 73, in app
    |     response = await f(request)
    |   File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 301, in app
    |     raw_response = await run_endpoint_function(
    |   File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 214, in run_endpoint_function
    |     return await run_in_threadpool(dependant.call, **values)
    |   File "/usr/local/lib/python3.9/dist-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    |     return await anyio.to_thread.run_sync(func)
    |   File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |   File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 2461, in run_sync_in_worker_thread
    |     return await future
    |   File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 962, in run
    |     result = context.run(func, *args)
    |   File "/root/sae/Sae_3A/python/script/Api/routers/books.py", line 255, in get_top_books
    |     top_books = bddservice.cmd_sql(query)
    |   File "/root/sae/Sae_3A/python/service/DatabaseService.py", line 226, in cmd_sql
    |     return self.cursor.fetchall()
    | psycopg2.ProgrammingError: no results to fetch
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 182, in __call__
    recv_stream.close()
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 179, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/root/sae/Sae_3A/python/script/Api/main.py", line 78, in dispatch
    return await call_next(request)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 154, in call_next
    raise app_exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/dist-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 2461, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 962, in run
    result = context.run(func, *args)
  File "/root/sae/Sae_3A/python/script/Api/routers/books.py", line 255, in get_top_books
    top_books = bddservice.cmd_sql(query)
  File "/root/sae/Sae_3A/python/service/DatabaseService.py", line 226, in cmd_sql
    return self.cursor.fetchall()
psycopg2.ProgrammingError: no results to fetch
Erreur lors de l'exécution de la commande SQL : no results to fetch
INFO:     46.193.64.108:56966 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56967 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56968 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56969 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56970 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56971 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56972 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56972 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56976 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56977 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56978 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56979 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56980 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56981 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56982 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56983 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56984 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56985 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56986 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56987 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56988 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56989 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56989 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56990 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56991 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56992 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56993 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56994 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56995 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56996 - "GET / HTTP/1.1" 200 OK
INFO:     46.193.64.108:56997 - "GET / HTTP/1.1" 200 OK
